main: cc.baka9.aloneopengui.Main
name: AloneOpenGui
version: 1.2
commands:
  aog:
    usage: |
            §a/<command> add  把手中的物品添加到方块识别列表
            §a/<command> del  把手中的物品从方块识别列表中移除
            §c/<command> addmenu  把手中的物品添加到菜单识别列表
            §c/<command> delmenu  把手中的物品从菜单识别列表中移除
            §6/<command> reload  重载插件