main: cc.baka9.aloneopengui.Main
name: AloneOpenGui
version: 1.1
commands:
  aog:
    usage: |
            §a/<command> add §c把手中的物品添加到禁止列表
            §a/<command> del §c把手中的物品从禁止列表中移除
            §a/<command> reload §c重载插件